### ISSUE TITLE
Error creating vignettes during R CMD build

### ISSUE THREAD

**Issue by kcha** [bioFAM/MOFA#14]
Hi, 

I'm getting the following error when trying to build MOFAtools:

```
> R CMD build MOFAtools
* checking for file ‘MOFAtools/DESCRIPTION’ ... OK
* preparing ‘MOFAtools’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR

Attaching package: 'MOFAtools'

The following object is masked from 'package:stats':

    predict

Quitting from lines 114-118 (MOFA_example_CLL.Rmd)
Error: processing vignette 'MOFA_example_CLL.Rmd' failed with diagnostics:
'x' must be an array of at least two dimensions
Execution halted
```

Digging a little deeper, it seems that the issue is in the `detectPassengers()` step of `loadModel()`. I think during the check for NULL `r2_threshold` in line 124, the example `CLL_model.hdf5` is missing the `object@TrainOptions$drop_by_r2` attribute and still returns NULL.

Thanks!

**Comment by bv2** [comment]
Hi,
thanks for reporting this error! You are right that there was a bug with the r2_threshold in TrainOptions when loading a model, which is called R2PerFactor not drop_by_r2 in the MOFA object. It should be fixed now, let us know this solves the issue.

**Comment by kcha** [comment]
This solves the issue during the build, thanks! Unfortunately, I'm now getting a similar error whenever I load one of my saved models:

```
> MOFAobject <- loadModel("my_model.hdf5")
Error in rowSums(r2 >= r2_threshold) : 
  'x' must be an array of at least two dimensions
```

However, it works if I prepare a MOFA object first:
```
> MOFAobject <- loadModel("my_model.hdf5", MOFAobject)
```

Thanks!

**Comment by bv2** [comment]
Hi,
thanks for the update! The problem were different names for the TrainOptions in the R and Python package of MOFA. We fixed this for now by renaming the TrainOptions to the R names when loading a model into R which fix your error. We will be working on making the names between the python and R options consistent.

**Comment by kcha** [comment]
Thanks for the fix!
