### ISSUE TITLE
Error for runMOFA

### ISSUE THREAD

**Issue by nitishkumarmishra** [bioFAM/MOFA#17]
Hi,
When I am using runMOFA I am getting this error--
MOFAobject <- runMOFA(MOFAobject, DirOptions = DirOptions)
Error in runMOFA(MOFAobject, DirOptions = DirOptions) : 
  mofa command failed with exit code 127

How to resolve this issue?

Thanks

**Comment by rargelaguet** [comment]
Hi Nitish,
DirOptions is from a depreciated old version of MOFA. You should use: 
```
runMOFA(MOFAobject, outfile)
```
Please have a look at the vignettes and the documentation on how to provide the Input/Output information
