### ISSUE TITLE
Error in runMOFA function

### ISSUE THREAD

**Issue by ashishjain1988** [bioFAM/MOFA#22]
I am getting the following error while running CLL example on my system.

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'module' object has no attribute 'core.entry_point'

I am using python 2.7.10 and R 3.4.3.

**Comment by rargelaguet** [comment]
I think the problem is that the MOFA python package is not properly installed. Can you open your python interpreter and check if you can import the mofa package?
If this works, can you restart R and try to load the package (from R) via reticulate (https://rstudio.github.io/reticulate/)?

**Comment by ashishjain1988** [comment]
I am able to import the "mofa" package both from the python interpreter and from R.

**Comment by ashishjain1988** [comment]
It's working on the UNIX system (RHEL) with python 2.7.5 and R 3.5. Earlier, I installed it on my MacBook having macOS Sierra. Is this package platform dependent?

**Comment by rargelaguet** [comment]
We tested it on the three common platforms and works fine. As long as the connection between R and python via reticulate is working, MOFA should run. I noticed that under some conditions one needs to restart R after installing the `mofa` python package. Let me know how it goes

**Comment by ashishjain1988** [comment]
I updated the OS and its working now. Thanks for all the help!!
