### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vijay-10x** [bioFAM/MOFA#25]
I thoroughly enjoyed reading your paper (including the very clear and detailed appendix that I appreciated) and your code. I work at 10x Genomics and I noticed that your code does not carry a license. I am interested in examining your methodology further and exploring potential applications to 10x data. Can you please add a license? I would appreciate it if you used a permissive license like MIT/BSD. Thank you.

**Comment by rargelaguet** [comment]
Thanks for your interest and I am glad you enjoyed the manuscript.
We have discussed and agreed to add a LGPL-3 license. It is not MIT, but I hope this is still useful for your purposes. If you want to explore/integrate MOFA with your platform, we will be happy to have a chat about it.

**Comment by vijay-10x** [comment]
Excellent, thank you for your prompt response. LGPL-3 works for us. We will be in touch with any questions or comments.
