### ISSUE TITLE
Feature request: FSEA direction of pathway/factor association

### ISSUE THREAD

**Issue by whitleyo** [bioFAM/MOFA#28]
Hi,

I've looked through the man pages and vignettes for the package, and it doesn't appear as if there's any functionality to determine the direction of association of a pathway with a factor. With runEnrichmentAnalysis, correct me if I'm wrong, but you get the result of a two sided test (p-value and adjusted p-value). For a biologist interested in characterizing what the sources of variation are in their data, the direction of association of pathways matter (e.g. how does location in the space of 2 factors determine how stem-like my samples are?). I think it might be a good idea to include the test statistic (e.g. mean difference statistic) in the output.

Thanks

**Comment by rargelaguet** [comment]
Good point, we will include this in the next couple of days.
For now, you could just color the factors by the expression of the individual genes from the significant pathways:

```plotFactorScatter(MOFAobject, factors = 1:2, color_by = "GENE_NAME")```

where GENE_NAME has to be a feature that is part of the training data.

**Comment by rargelaguet** [comment]
Now we include the test statistics in the `runEnrichment` output and we provide a new function to inspect which genes are driving the signal for each pathway. See `plotEnrichmentDetailed`.
