### ISSUE TITLE
Trouble Installing MOFA in R

### ISSUE THREAD

**Issue by AmyLei96** [bioFAM/MOFA#29]
Hello,

I am receiving the following errors when installing MOFA (MOFAdata was fine):

Warning: no function found corresponding to methods exports from ‘GenomicRanges’ for: ‘concatenateObjects’
Warning: replacing previous import ‘BiocGenerics::dims’ by ‘Biobase::dims’ when loading ‘SummarizedExperiment’
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘rhdf5’ 2.24.0 is being loaded, but >= 2.27.11 is required
ERROR: lazy loading failed for package ‘MOFA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/MOFA’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/8p/q0ycmsjn24z_lhggnht49nmm0000gn/T//RtmpdUtTas/file86229c13e3f/MOFA_0.99.5.tar.gz’ had non-zero exit status

**Comment by rargelaguet** [comment]
It is an error in the dependencies. From the error message I would bet that you need to update the rhdf5 package:
```namespace ‘rhdf5’ 2.24.0 is being loaded, but >= 2.27.11 is required```

**Comment by rargelaguet** [comment]
I have updated the rhdf5 version requirements, now it should work. Can you try again?

**Comment by AmyLei96** [comment]
I had updated the rhdf5 package before and it still didn't work, but after your updating the version requirements, it works. Thank you!

**Comment by rargelaguet** [comment]
Great, I think there has been a mistake on the last commit which I now reversed. Apologies!
