### ISSUE TITLE
Missing for loop

### ISSUE THREAD

**Issue by VIGS25** [bioFAM/MOFA#35]
https://github.com/bioFAM/MOFA/blob/c20929be1ba5659fce9d93780071501962790934/mofapy/core/distributions.py#L168

In the above referenced line, it looks like a for-loop is missing, since the variable `n` is used but not defined within the function.

**Comment by rargelaguet** [comment]
This is correct, thanks for the heads up!
But just to clarify, currently we don't use multivariate normals so this line should not intervene at all .

**Comment by VIGS25** [comment]
Thanks for the quick response, and the clarification!
