### ISSUE TITLE
function "plotTilesData" not included in MOFA package from BiocManager

### ISSUE THREAD

**Issue by SBassler** [bioFAM/MOFA#40]
After installing MOFA successfully and running some of the functions, plotTilesData still not available:
Error in plotTilesData(MOFAobject, colors = cols4omics) : 
  could not find function "plotTilesData"

**Comment by rargelaguet** [comment]
ups I completely forgot to reply to this, sorry.

The function `plotTilesData` has been renamed to `plotDataOverview`

**Comment by SBassler** [comment]
alright, thank you!
