### ISSUE TITLE
Enrichment analysis with HUGO symbols

### ISSUE THREAD

**Issue by merlevede** [bioFAM/MOFA#42]
Hello,

I am trying your tools on few datasets. For all of them, I have HUGO symbols for feature names.
So when trying to perform feature set enrichment analysis, I get an error:
>gsea <- runEnrichmentAnalysis(
>   MOFAobject,
>   view = "mRNA",
>   feature.sets = reactomeGS,
>   alpha = 0.01
> )
Error in runEnrichmentAnalysis(MOFAobject, view = "mRNA", feature.sets = reactomeGS,  : 
  Feautre names in feature.sets do not match feature names in model.

Is there a way to use HUGO symbols instead of ensembl annotations for feature.sets for enrichment analysis (using Reactome or other databases)?

Thank you in advance,
Jane

**Comment by rargelaguet** [comment]
Hi Jane,

You have two options:
(1) use the gene set annotations that I prepared, but you will have to manually convert the ensemble IDs to HUGO IDs.
(2) create your own gene set annotations with HUGO IDs and provide them as input to `runEnrichmentAnalysis`. The format is a binary matrix with pathways in the rows and features in the columns.

**Comment by merlevede** [comment]
Thank you for your answer. I will then convert the ID given in feature.sets.
It might be user friendly to give the choice between annotations if there is a next release of MOFA.
