### ISSUE TITLE
Documentation missmatch for getDefaultModelOptions()$numFactors

### ISSUE THREAD

**Issue by frederikziebell** [bioFAM/MOFA#51]
Hi Britta and Ricard,

I'm running MOFA 1.2.0. 
The documentation says the default value of `numFactors` in `getDefaultModelOptions()` is 25, but the source code says `numFactors = ceiling(nsamples/2)`. I also looked in the source of the current master branch and there it says `numFactors = 10` although the documentation still says 25. 

Best wishes,
Frederik

**Comment by rargelaguet** [comment]
Hi Frederik,
thanks for the heads up. We realised that numFactors = ceiling(nsamples/2) was to large, so we changed it, but apparently we forgot to modify the documentation accordingly.

P.S. We will release MOFA v2 in the next couple of days. Make sure to check the improved implementation :)
