### ISSUE TITLE
error message: mofapy package not found.

### ISSUE THREAD

**Issue by squirrelB** [bioFAM/MOFA#58]
Hi. I'm on a Mac. Not a python user, so this has me stuck. I've installed Python 3, and mofapy. Below is the printout from my terminal showing the PATH to Python 3.8 and also verifies that mofapy is indeed installed (screen shot below). However, when I run R, I still get an error (screenshot at the end). I'm not sure what I'm doing wrong. Wondering if this is a Mac issue or I'm just pointing use_python to the wrong path.

<img width="659" alt="Screen Shot 2020-09-08 at 8 59 19 PM" src="https://user-images.githubusercontent.com/31778385/92545931-e39ad980-f216-11ea-8ee0-b27bfac6083e.png">

<img width="874" alt="Screen Shot 2020-09-08 at 9 05 20 PM" src="https://user-images.githubusercontent.com/31778385/92545987-0c22d380-f217-11ea-84ca-c0d13b3c88b6.png">

**Comment by rargelaguet** [comment]
Hi @squirrelB,
in use_python you need to point to the actual python binary, not just the directory. Also, use the `required=TRUE` argument. Let me know if this works.

Please note that this repository is no longer mantained, please move to [MOFA2](https://github.com/bioFAM/MOFA2)

**Comment by squirrelB** [comment]
Solved the issue. Thanks! My directory path was incorrect. 
First, in the Unix terminal:
sb@sbmacbook ~ % which python3
/usr/local/bin/python3

In R: use_python("/usr/local/bin/python3", required = TRUE)
Now it's running. Thanks!
And thanks for the heads up about MOFA2.
