### ISSUE TITLE
Factors should have names starting with a letter

### ISSUE THREAD

**Issue by DarwinAwardWinner** [bioFAM/MOFA#8]
Currently, factors in a MOFA model have names that are string representations of integers, which is a bad idea. It means that `getFactors(mofa, 2)` and `(getFactors(mofa, "2")` return different results. I would recommend that you prepend a lettered prefix to each factor name, e.g. "LF" for latent factor, such that there is less confusion between numeric and character indices.

**Comment by rargelaguet** [comment]
I totally agree, will update this asap.

**Comment by rargelaguet** [comment]
This should be fixed now. Rather than appending LF we modified the code so that `getFactors(mofa,1)` and `getFactors(mofa,"1")` return always Factor "1". Perhaps is a good idea to append LF but it will add some redundancy, so I am not totally convinced.

**Comment by DarwinAwardWinner** [comment]
The main rationale for prepending "LF" to the names is to make it impossible to confuse the names with numbers. For example, it makes sure that `as.numeric` returns NA instead of numbers. Basically, it's considered bad practice in R to use a name that couldn't be used as a variable name (without backticks).

**Comment by damienArnol** [comment]
I agree with adding ‘LF’. Another potential trouble I had with having only numbers for the factors is that if you want to build your own plotting tools on the top of MOFATools, you might have trouble with packages such as ggplot if you want to use the factor indices as aesthetics. Im sure that in many other cases it will be really good to have non-ambiguous factor names with strings.

**Comment by rargelaguet** [comment]
Ok you convinced me, will do this for the next update.

**Comment by bv2** [comment]
Factor names were changed to 'LFx'. Functions can be called either with getFactors(mofa,1) or getFactors(mofa,"LF1") etc.
